### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by skulltech** [webcompat/issue_parser#10]
This project is to be used by other projects, and for maximum compatibility Python 3 support should be added. One example of such project would be [autowebcompat](https://github.com/marco-c/autowebcompat), which works with Python 3.

**Comment by skulltech** [comment]
Also, I was wondering, if support for Python 2 can be dropped. If we drop support for Python 2, reading and writing to and from files can be much easier, and issues like #12 can be fixed gracefully (without any need for silly hacks).

**Comment by karlcow** [comment]
@SkullTech So the issue_parser code here is not really maintained. As it was more of a one off script. 

BUT we can probably work together on something if we better understand the needs. I'm jumping to your issue.

**Comment by karlcow** [comment]
So I browsed a bit the code here and there. I have seen you have used code directly from the project. Maybe we can come up with something that will minimize maintaining code at multiple places.

That's a good thing. 

@SkullTech @marco-c Could you open an issue on https://github.com/webcompat/webcompat.com/issues/new with an explanation of which type of data would be interesting for you from the webcompat.com project so we can see if we can make it easier for you.

Thanks. ping @miketaylr

**Comment by karlcow** [comment]
> if support for Python 2 can be dropped

@SkullTech Yes. But there is a larger question on how to make the webcompat.com data useful to you in the first place.

**Comment by miketaylr** [comment]
+1.

**Comment by skulltech** [comment]
@karlcow I'm gonna make this code usable so that we can continue working until we can get the webcompat data in a better and more proper way. Meanwhile, as you suggested, we're gonna raise an issue there. :)

**Comment by skulltech** [comment]
Opened [an issue](https://github.com/webcompat/webcompat.com/issues/2048) at the webcompat.com repo as @karlcow suggested.
