### ISSUE TITLE
Encoding issue while writing to file

### ISSUE THREAD

**Issue by skulltech** [webcompat/issue_parser#12]
Below is the error message which came upon running
```console
$ python2 extract_id_title_url.py
```

The error message being
```console
Traceback (most recent call last):
  File "extract_id_title_url.py", line 174, in <module>
    sys.exit(main())
  File "extract_id_title_url.py", line 163, in main
    f.write("\n".join(results).encode('utf8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1818: ordinal not in range(128)
```

**Comment by karlcow** [comment]
Ah I see you have been using the old issue_parser in your project. The data structure changed a lot since the first writing of this code. We don't rely on the same data. Ok let's try to see if we can fix things together.
