### ISSUE TITLE
Remove db from requirements.txt

### ISSUE THREAD

**Issue by karlcow** [webcompat/issue_parser#17]
@SkullTech in #10 we forgot to remove db from requirements.txt. My bad for not spotting it.

**Comment by skulltech** [comment]
Okay making a pull-request now.

**Comment by skulltech** [comment]
I think we should also remove the version info of `SQLAlchemy`. Or at least update it to the latest stable version. What do you think? @karlcow

**Comment by karlcow** [comment]
plus one on adjusting to the latest version of SQLAlchemy. Make sure it is working in doing so.
