### ISSUE TITLE
The extract_id_title_url.py script doesn't work

### ISSUE THREAD

**Issue by marco-c** [webcompat/issue_parser#2]
It logs a bunch of issues and then:

```
Wrote 0 items to webcompatdata.csv 
Wrote 0 items to webcompatdata-bzlike.json
```

**Comment by hallvors** [comment]
I've been wondering why webcompat issues were no longer appearing on the arewecompatibleyet.com site - thanks for debugging that problem before I got to it! :-D

**Comment by marco-c** [comment]
@hallvors there are other usages of labels_list in the function that may be wrong (I haven't actually checked them: `whiteboard` and `resolution`)

**Comment by hallvors** [comment]
Reviewed, seems OK.
